apiVersion: v1
kind: Service
metadata:
  name: {{.Values.externalService.name }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "metastore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - name: {{ .Values.externalService.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
  {{- include "metastore.selectorLabels" . | nindent 4 }}