---
  {{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metastore.fullname" . }}-spark
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "metastore.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
    verbs:
      - "*"
  {{- end }}

---
  {{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metastore.fullname" . }}-spark
  labels:
  {{- include "metastore.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "metastore.fullname" . }}-spark
subjects:
  - name:  {{ include "metastore.sparkServiceAccountName" . }}
    kind: ServiceAccount
  {{- end }}