{{- if .Values.serviceAccounts.spark.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metastore.sparkServiceAccountName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "metastore.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.spark.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}