apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "metastore.fullname" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "metastore.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "metastore.fullname" . }}-thrift
  selector:
    matchLabels:
    {{- include "metastore.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metastore.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: thrift
              containerPort: 9083
              protocol: TCP
          command: ["/bin/sh","-c"]
          args: ["/opt/entrypoint.sh"]
          volumeMounts:
            - name: metastore-config
              mountPath: /opt/hive/conf
      volumes:
        - name: metastore-config
          configMap:
            name: {{ include "metastore.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
       {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}