{{- $secret := (lookup "v1" "Secret" .Values.mysqlNamespace .Values.mysqlSecret) -}}
  {{ if ( and (.Values.mysqlDB) $secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hiveSecret }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "common.labels" (dict "componentName" .Values.hiveSecret "namespace" .Release.Namespace ) | nindent 4 }}
data:
  hive-site.xml: {{ $secret.data.hivesite }}
  {{ end }}