{{ $componentName := .Chart.Name }}
{{ $configmapName := printf "%s-cm" .Chart.Name }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $componentName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
spec:
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  serviceName:  {{ $componentName }}-svc
  selector:
    matchLabels:
  {{- include "common.selectorLabels" (dict "componentName" $componentName ) | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "common.labels" (dict "componentName" $componentName "namespace" .Release.Namespace ) | nindent 8 }}
    spec:
      subdomain: {{ $componentName }}-svc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{-  include "common.nodeAffinity.preferred" . | nindent 12 }}
          requiredDuringSchedulingIgnoredDuringExecution:
        {{-  include "common.nodeAffinity.required" . | nindent 12 }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{-  include "common.podAntiAffinity.preferred" (dict "componentName" $componentName ) | nindent 12 }}
      tolerations:
      {{- include "common.tolerations" (dict "componentName" $componentName "namespace" .Release.Namespace ) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
  {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hivemeta-chart.serviceAccountName" . | nindent 8}}
      restartPolicy: {{ .Values.restartPolicy }}
      priorityClassName: "hpe-tenant-service"
      initContainers: []
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken  }}
      containers:
        - name: {{ $componentName }}
          args:
          {{- include "common.args" . | nindent 12 }}
          command:
          {{- include "common.commands" . | nindent 12 }}
          env:
          {{- include "hivemeta-chart.env" . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- include "hivemeta-chart.ports" . | nindent 12 }}
          livenessProbe:
          {{- include "common.probe.liveness" . | nindent 12 }}
          readinessProbe:
          {{- include "common.probe.readiness" . | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
          {{- include "common.securityContext" . | nindent 12 }}
          volumeMounts:
          {{- if .Values.mysqlDB }}
          {{- include "hivemeta-chart.secretVolumeMount" . | nindent 12 }}
          {{- end}}
          {{- include "hivemeta-chart.volumeMounts" . | nindent 12 }}
      volumes:
      {{- if .Values.mysqlDB }}
      {{- include "hivemeta-chart.secretVolume" . | nindent 8 }}
      {{- end }}
      {{- include "common.volumes" (dict "configmapName" $configmapName "componentName" $componentName) | nindent 8 }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
