# Default values for metastore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/mapr-252711/apache-metastore-2.3.8
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "202107071551"

imagePullSecrets:
  - name: imagepull

createDefaultPullSecret: true

defaultPullSecret: imagepull

serviceAccounts:
  metastore:
    create: true
    annotations: {}
    name: ""
  spark:
    create: true
    annotations: {}
    name: ""

ownerReference:
  overRide: false
  ownerReferences: {}

rbac:
  create: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9083
  name: "metastore-int-svc"

externalService:
  type: NodePort
  name: "metastore-ext-svc"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# -- Set this if running spark jobs in a different namespace than the operator
sparkJobNamespace: ""

nodeSelector: {}

tolerations: []

affinity: {}
